[book]
  title = "ChirpStack open-source LoRaWAN® Network Server documentation"
  authors = []
  language = "en"
  src = "src"

[output.html]
  no-section-label = true
  additional-css = ["theme/css/chirpstack.css"]
  git-repository-url = "https://github.com/chirpstack/chirpstack-docs"
  git-repository-icon = "fab-github"
  edit-url-template = "https://github.com/chirpstack/chirpstack-docs/edit/master/{path}"
  default-theme = "light"

  [output.html.print]
    enable = false

  [output.html.fold]
    enable = true
    level = 0

[preprocessor.d2]
  path = "d2"
  inline = false

[preprocessor.findrep]
  chirpstack_version = "4.18.0"
  gateway_os_version = "4.11.0"
  gateway_bridge_version = "4.1.1"
  concentratord_version = "4.7.1"
  mqtt_forwarder_version = "4.5.1"
  pulsar_integration_version = "4.0.0-test.3"
  gateway_mesh_version = "4.1.3"
