FROM rust:1.72.0-buster

WORKDIR /chirpstack-docs


RUN cargo install mdbook
RUN cargo install mdbook-tera
RUN cargo install mdbook-graphviz
RUN cargo install mdbook-toc

RUN apt-get update && apt-get install -y graphviz
