FROM rust:1.81.0-bookworm

WORKDIR /chirpstack-docs


RUN cargo install mdbook@0.4.48
RUN cargo install mdbook-tera
RUN cargo install mdbook-graphviz
RUN cargo install mdbook-toc

RUN apt-get update && apt-get install -y graphviz
